import { App } from 'vue';
import {
    ElButton,
    ElRow,
    ElCol,
    ElSubmenu,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElIcon,
    ElContainer,
    ElAside,
    ElMain,
    ElForm,
    ElFormItem,
    ElInput,
    ElSelect,
    ElOption,
    ElTable,
    ElTableColumn,
    ElPagination,
    ElDialog,
    ElCascader,
    ElSwitch,
    ElUpload,
    ElMessage,
    ElTag,
    ElDropdown,
    ElDropdownItem,
    ElInputNumber,
} from 'element-plus';

export const installComponents = [
    ElButton,
    ElRow,
    ElCol,
    ElSubmenu,
    ElMenu,
    ElMenuItem,
    ElMenuItemGroup,
    ElIcon,
    ElContainer,
    ElAside,
    ElMain,
    ElForm,
    ElFormItem,
    ElInput,
    ElSelect,
    ElOption,
    ElTable,
    ElTableColumn,
    ElPagination,
    ElDialog,
    ElCascader,
    ElSwitch,
    ElUpload,
    ElMessage,
    ElTag,
    ElDropdown,
    ElDropdownItem,
    ElInputNumber,
];
export const elementUI = {
    install(app: App) {
        installComponents.forEach((item: { name: string | undefined }) => {
            app.component(item.name || '', item);
        });
    },
};
